resources:
  repositories:
  - repository: PipelineTemplates
    type: github
    endpoint: con1
    name: sauravt01/PipelineTemplates
    ref: refs/heads/main
    

    
pool: Mera Pool
stages:
  - stage: 
    displayName: stage1
    jobs:
      - job: 
        steps:
        - template: build-template.yml@PipelineTemplates