parameters:
  - name: x
    displayName: x naam ka parameter hai
    type: string
    default: gaurav
    # values: 
    # - " "
    # - saurav

pool: Mera Pool
stages:
  - stage: 
    displayName: stage1
    jobs:
      - job: 
        steps:
          - powershell: echo ${{ parameters.x }}