trigger: none
variables: 
  - group: G34
  # # - template: azure-pipelines.yml
  # - name: x
  #   value: 10 
  # - name: y
  #   value: 20
  # - name: z
  #   value: 30
  # - name: name
  #   value: 'saurav'

  
pool: Mera Pool
stages:
- stage: Stage1
  jobs:
  - job: Job1
    
    steps:
    - powershell: echo $(Q)
    - powershell: echo $(P), $(lastname)

    - powershell: echo $(add) ` $(L)
    # - powershell: echo $(name)

- stage: stage2 
  jobs:
    - job: 
      variables:
      - group: G35
      steps:
        - powershell: echo $(L)
        - powershell: echo $(P)
         
 


