variables: 
  - group: G34
  # - group: G35
  # # - template: azure-pipelines.yml
  # - name: x
  #   value: 10 
  # - name: y
  #   value: 20
  # - name: z
  #   value: 30
  # - name: name
  #   value: 'saurav'

  
pool: Mera Pool
stages:
- stage: Stage1
  jobs:
  - job: Job1
    
    steps:
    - powershell: echo $(Q)
    - powershell: echo $(P), $(lastname)
    # - powershell: echo $(x) ` $(z)
    # - powershell: echo $(name)

