

resources:
  repositories:
  - repository: PipelineTemplates
    type: github
    name: sauravt01/PipelineTemplates
    endpoint: con1
    ref: refs/heads/main


trigger:
- main

pool: Mera Pool

jobs:
- job: DemoJob
  steps:

  - template: build-template.yml@PipelineTemplates
    parameters:
      projectName: "My Demo Project"
      message: "Hello from Main Pipeline"

